version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/.github/"
    schedule:
      interval: "weekly"
      day: "sunday"
    rebase-strategy: disabled
    reviewers:
      - "soumeh01"
      - "brondani"

  # Go modules updates (daily)
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "soumeh01"
      - "brondani"
