version: 2
updates:
  # GitHub Actions updates (weekly)
  - package-ecosystem: github-actions
    directory: "/.github/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "08:00"
    rebase-strategy: disabled
    labels:
      - "dependencies"
      - "automated"
    reviewers:
      - "soumeh01"

  # Go modules updates (weekly)
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "08:00"
    open-pull-requests-limit: 5
    groups:
      minor-and-patch-updates:
        patterns:
          - "*"
        update-types: ["minor", "patch"]
    labels:
      - "dependencies"
    reviewers:
      - "soumeh01"
    commit-message:
      prefix: "chore(deps)"

  # Security updates (keep immediate security fixes)
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "security"
    reviewers:
      - "soumeh01"
    commit-message:
      prefix: "fix(security)"
