/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.0.0-dev2
 *
 * Project: 'test1.Debug+CM3' 
 * Target:  'Debug+CM3' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "ARMCM3.h"



#endif /* RTE_COMPONENTS_H */
