name: markdown
on:
  pull_request:
    paths:
      - '.github/workflows/markdown.yml'
      - '.github/markdownlint.json'
      - '.github/markdownlint.jsonc'
      - '**/*.md'

permissions:
  contents: read

jobs:
  markdown-check:
    name: Markdown Check 
    uses: soumeh01/infra-library/.github/workflows/markdown.yml@main
    with:
      lint: true
      link-check: true
