name: Run Gosec
on:
  pull_request:
    paths:
      - '.github/workflows/security.yml'
      - 'cmd/**'
      - 'pkg/**'
      - 'test/**'
      - 'go.mod'
      - 'go.sum'
      - '!**/*.md'
  push:
    branches: [ main ]

permissions: read-all

jobs:
  gosec:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on

    steps:
      - name: Checkout Source
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Run Gosec Security Scanner
        uses: securego/gosec@e0cca6fe95306b7e7790d6f1bf6a7bec6d622459 # v2.22.0
        with:
          args: './...'
